# Generated by Django 5.2.8 on 2025-11-16 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPointsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_points', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('withdrawal_method', models.CharField(help_text='e.g. UPI, Bank Transfer, Paytm, etc.', max_length=50)),
                ('withdrawal_details', models.TextField(help_text='JSON or formatted details for the chosen withdrawal method.')),
                ('withdrawal_pin_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('kyc_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_document_file', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('referral_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('referral_link_slug', models.SlugField(help_text='Used to build referral URLs.', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
