# Generated by Django 5.2.8 on 2025-11-16 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cycle_days', models.PositiveIntegerField(help_text='Investment cycle length in days.')),
                ('daily_return_percent', models.DecimalField(decimal_places=2, help_text='Daily return % on invested amount (e.g. 1.5 = 1.5% per day).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('terms_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('last_return_date', models.DateField(blank=True, null=True)),
                ('personal_wallet_debit_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_principal_debit', to='wallets.wallettransaction')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_investments', to='investments.investmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wallet_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallettransaction')),
                ('user_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='investments.userinvestment')),
            ],
            options={
                'unique_together': {('user_investment', 'date')},
            },
        ),
    ]
