# Generated by Django 5.2.8 on 2025-11-16 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_url', models.URLField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usertask',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User rating (1–5 stars).', null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='code',
            field=models.CharField(choices=[('RATE_MOVIE', 'rate_movie'), ('RATE_PROPERTY', 'rate_property')], default='RATE_MOVIE', max_length=50),
        ),
        migrations.AddField(
            model_name='usertask',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.movie'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='property_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.propertylisting'),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'task_type', 'date', 'movie'), name='unique_movie_task_per_day'),
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(condition=models.Q(('property_listing__isnull', False)), fields=('user', 'task_type', 'date', 'property_listing'), name='unique_property_task_per_day'),
        ),
    ]
